### ISSUE TITLE
how to perform debugging in pycharm?

### ISSUE THREAD

**Issue by hwan-sig** [Erosinho13/FedDrive#4]
Hi. I am trying to perform debugging to understand codes.
However, in PyCharm environments, I can't perform debugging because of shell file.
could you help?

error message is "/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 87, in __post_init__
    assert self.local_world_size > 0
AssertionError"

environment variable:
CUDA_VISIBLE_DEVICES=0

interpreter option:
-W ignore -m torch.distributed.launch --nproc_per_node 0 --master_port=2509

parameters:
--name idda_heterogeneous_country --device_ids 1 --random_seed 42 --wandb_entity FedDrive --mixed_precision --ignore_warnings --save_samples --avg_last_100 --dataset idda --clients_type heterogeneous --setting_type country --remap --framework federated --algorithm FedAvg --num_rounds 1600 --clients_per_round 5 --num_epochs 2 --model bisenetv2 --output_aux --hnm --batch_size 16 --test_batch_size 1 --test_diff_dom --optimizer SGD --weight_decay 0 --momentum 0.9 --lr 0.1 --lr_policy poly --lr_power 0.9 --rrc_transform --use_test_resize --min_scale 0.5 --max_scale 2.0 --h_resize 512 --w_resize 928 --eval_interval 30000 --test_interval 50 --print_interval 50

**Comment by Erosinho13** [comment]
Hi, thank you for your interest in our code. Unfortunately, this is a well-known issue with pycharm when using DDP. You can refer to the following resources:
- https://github.com/open-mmlab/mmdetection/issues/992
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003286359-Debugging-with-multiprocess-causes-exception-in-Pycharm
